# Friends controller

### Index
GET http://localhost:3000/friend


### Show
GET http://localhost:3000/friend/2


### Create
POST http://localhost:3000/friend
Content-Type: application/json

{
  "name": "Tanner",
  "description": "The tall one",
  "score": 0
}


### Update
PATCH http://localhost:3000/friend/1
Content-Type: application/json

{
  "name": "Tanner",
  "description": "The tall one",
  "score": 100
}

### Destroy
DELETE http://localhost:3000/friend/1


# Deeds Controller

### Index
GET http://localhost:3000/deed


### Show
GET http://localhost:3000/deed/2


### Create
POST http://localhost:3000/deed
Content-Type: application/json

{
  "deed": "Gave cookie",
  "description": "Freshly baked",
  "good": true,
  "friend_id": 2
}


### Update
PATCH http://localhost:3000/deed/1
Content-Type: application/json

{
  "deed": "Gave 2 cookies",
  "description": "Freshly baked",
  "good": true,
  "friend_id": 2
}

### Destroy
DELETE http://localhost:3000/deed/1